version: '3'
volumes:
  nginx_conf:
    external:
        name: nginx_conf
  nginx_vhost:
    external:
        name: nginx_vhost
  nginx_html:
    external:
        name: nginx_html
  nginx_certs:
    external:
        name: nginx_certs
  transmission_config:
    external:
        name: transmission_config
  downloads:
    external:
        name: downloads
  transmission_watch:
    external:
        name: transmission_watch
  sonarr_config:
    external:
        name: sonarr_config
  tvseries:
    external:
        name: tvseries
  portainer_data:
    external:
        name: portainer_data
  movies:
    external:
        name: movies
  couchpotato_config:
    external:
        name: couchpotato_config
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_web
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen:latest
    command: -notify-sighup nginx_web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx_gen
    restart: always
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: nginx_letsencrypt
    restart: always
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx_gen
      NGINX_PROXY_CONTAINER: nginx_web

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      VIRTUAL_HOST: portainer.parmalen.com
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: parmalen.com,www.parmalen.com,portainer.parmalen.com,tv.parmalen.com,torrents.parmalen.com,movies.parmalen.com
      LETSENCRYPT_EMAIL: iglinsek@gmail.com
  
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: always
    volumes:
      - transmission_config:/config
      - downloads:/downloads
      - transmission_watch:/watch
    environment:
      PGID: 0
      PUID: 0
      TZ: America/Buenos_Aires  
      VIRTUAL_HOST: torrents.parmalen.com
      VIRTUAL_PORT: 9091
      LETSENCRYPT_HOST: parmalen.com,www.parmalen.com,portainer.parmalen.com,tv.parmalen.com,torrents.parmalen.com,movies.parmalen.com
      LETSENCRYPT_EMAIL: iglinsek@gmail.com

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - sonarr_config:/config
      - tvseries:/tv
      - downloads:/downloads
    environment:
      PGID: 0
      PUID: 0
      TZ: America/Buenos_Aires
      VIRTUAL_HOST: tv.parmalen.com
      VIRTUAL_PORT: 8989
      LETSENCRYPT_HOST: parmalen.com,www.parmalen.com,portainer.parmalen.com,tv.parmalen.com,torrents.parmalen.com,movies.parmalen.com
      LETSENCRYPT_EMAIL: iglinsek@gmail.com

  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    restart: always
    volumes:
      - couchpotato_config:/config
      - downloads:/downloads
      - movies:/movies
    environment:
      PGID: 0
      PUID: 0
      TZ: America/Buenos_Aires
      VIRTUAL_HOST: movies.parmalen.com
      VIRTUAL_PORT: 5050
      LETSENCRYPT_HOST: parmalen.com,www.parmalen.com,portainer.parmalen.com,tv.parmalen.com,torrents.parmalen.com,movies.parmalen.com
      LETSENCRYPT_EMAIL: iglinsek@gmail.com

networks:
  default:
    external:
      name: webproxy
