version: '3'
volumes:
  nginx_conf:
    external:
        name: ${VOLUME_NGINX_CONF}
  nginx_vhost:
    external:
        name: ${VOLUME_NGINX_VHOST}
  nginx_html:
    external:
        name: ${VOLUME_NGINX_HTML}
  nginx_certs:
    external:
        name: ${VOLUME_NGINX_CERTS}
  transmission_config:
    external:
        name: ${VOLUME_TRANSMISSION_CONFIG}
  transmission_watch:
    external:
        name: ${VOLUME_TRANSMISSION_WATCH}
  downloads:
    external:
        name: ${VOLUME_DOWNLOADS}  
  sonarr_config:
    external:
        name: ${VOLUME_SONARR_CONFIG}
  tvseries:
    external:
        name: ${VOLUME_TVSERIES}
  portainer_data:
    external:
        name: ${VOLUME_PORTAINER_DATA}
  movies:
    external:
        name: ${VOLUME_MOVIES}
  couchpotato_config:
    external:
        name: ${VOLUME_COUCHPOTATO_CONFIG}
  htpcmanager_config:
    external:
        name: ${VOLUME_HTPCMANAGER_CONFIG}
services:
  nginx:
    image: nginx:alpine
    container_name: ${NGINX_WEB_CONTAINER_NAME}
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen:latest
    command: -notify-sighup ${NGINX_WEB_CONTAINER_NAME} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${NGINX_GEN_CONTAINER_NAME}
    restart: always
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: ${NGINX_LETSENCRYPT_CONTAINER_NAME}
    restart: always
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${NGINX_GEN_CONTAINER_NAME}
      NGINX_PROXY_CONTAINER: ${NGINX_WEB_CONTAINER_NAME}

  portainer:
    image: portainer/portainer
    container_name: ${PORTAINER_CONTAINER_NAME}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      VIRTUAL_HOST: ${PORTAINER_VIRTUAL_HOST}
      VIRTUAL_PORT: 9000
  
  transmission:
    image: linuxserver/transmission
    container_name: ${TRANSMISSION_CONTAINER_NAME}
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: always
    volumes:
      - transmission_config:/config
      - downloads:/downloads
      - transmission_watch:/watch
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIME_ZONE}
      VIRTUAL_HOST: ${TRANSMISSION_VIRTUAL_HOST}
      VIRTUAL_PORT: 9091

  sonarr:
    image: linuxserver/sonarr
    container_name: ${SONARR_CONTAINER_NAME}
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - sonarr_config:/config
      - tvseries:/tv
      - downloads:/downloads
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIME_ZONE}
      VIRTUAL_HOST: ${SONARR_VIRTUAL_HOST}
      VIRTUAL_PORT: 8989

  couchpotato:
    image: linuxserver/couchpotato
    container_name: ${COUCHPOTATO_CONTAINER_NAME}
    restart: always
    volumes:
      - couchpotato_config:/config
      - downloads:/downloads
      - movies:/movies
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIME_ZONE}
      VIRTUAL_HOST: ${COUCHPOTATO_VIRTUAL_HOST}
      VIRTUAL_PORT: 5050

  htpcmanager:
    image: linuxserver/htpcmanager
    container_name: ${HTPCMANAGER_CONTAINER_NAME}
    volumes:
      - htpcmanager_config:/config
    environment:
      VIRTUAL_HOST: ${HTPCMANAGER_VIRTUAL_HOST}
      VIRTUAL_PORT: 8085
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      TZ: ${TIME_ZONE}
      PGID: ${PGID}
      PUID: ${PUID}

networks:
  default:
    external:
      name: ${NETWORK}
